import { getScenario } from "@/lib/detection/scenarios";

export class SandboxSourceError extends Error {
  constructor(message, { code, status = 503, risk = 50, scenarioId }) {
    super(message);
    this.name = "SandboxSourceError";
    this.code = code;
    this.status = status;
    this.risk = risk;
    this.scenarioId = scenarioId;
  }
}

export const sandboxSource = {
  name: "LinkedIn-like Detection Sandbox",

  async fetchJobs({
    scenarioId = "normal",
    limit = 20,
    requestCount = 1,
    timeoutMs = 1200,
  } = {}) {
    const scenario = getScenario(scenarioId);

    if (scenario.id === "timeout") {
      await new Promise((resolve) => setTimeout(resolve, timeoutMs + 50));
      throw new SandboxSourceError(
        "Sandbox request exceeded the configured timeout.",
        {
          code: "TIMEOUT",
          status: 504,
          risk: scenario.risk,
          scenarioId: scenario.id,
        },
      );
    }

    if (scenario.id === "rate_limit") {
      throw new SandboxSourceError(
        "Sandbox returned HTTP 429: simulated request-frequency limit.",
        {
          code: "RATE_LIMIT",
          status: 429,
          risk: scenario.risk,
          scenarioId: scenario.id,
        },
      );
    }

    if (scenario.id === "server_error") {
      throw new SandboxSourceError(
        "Sandbox returned HTTP 503: simulated temporary upstream failure.",
        {
          code: "UPSTREAM_5XX",
          status: 503,
          risk: scenario.risk,
          scenarioId: scenario.id,
        },
      );
    }

    if (scenario.id === "header_anomaly") {
      throw new SandboxSourceError(
        "Sandbox rejected the simulated request profile.",
        {
          code: "HEADER_ANOMALY",
          status: 403,
          risk: scenario.risk,
          scenarioId: scenario.id,
        },
      );
    }

    if (scenario.id === "behavior_anomaly") {
      throw new SandboxSourceError(
        "Sandbox detected a simulated repetitive request pattern.",
        {
          code: "BEHAVIOR_ANOMALY",
          status: 403,
          risk: scenario.risk,
          scenarioId: scenario.id,
        },
      );
    }

    if (scenario.id === "session_anomaly") {
      throw new SandboxSourceError(
        "Sandbox detected inconsistent simulated session state.",
        {
          code: "SESSION_ANOMALY",
          status: 403,
          risk: scenario.risk,
          scenarioId: scenario.id,
        },
      );
    }

    if (scenario.id === "challenge") {
      throw new SandboxSourceError(
        "Sandbox returned a simulated challenge/CAPTCHA requirement.",
        {
          code: "CHALLENGE_REQUIRED",
          status: 403,
          risk: scenario.risk,
          scenarioId: scenario.id,
        },
      );
    }

    if (scenario.id === "schema_change") {
      return {
        unexpectedItems: createJobs(Math.min(limit, 5)),
      };
    }

    if (scenario.id === "empty_response") {
      return [];
    }

    return createJobs(Math.min(limit, 20));
  },
};

function createJobs(limit) {
  return Array.from({ length: limit }, (_, index) => ({
    id: `sandbox-${index + 1}`,
    title: [
      "Frontend Engineer",
      "Software Engineer",
      "Product Engineer",
      "Data Engineer",
      "Staff Software Engineer",
    ][index % 5],
    company: [
      "Sandbox Technologies",
      "Example Labs",
      "Demo Systems",
      "Resilience Works",
      "Acme Platform",
    ][index % 5],
    location: index % 2 === 0 ? "Remote" : "Berlin",
    url: `https://example.com/jobs/sandbox-${index + 1}`,
    description:
      "Synthetic job record generated by the controlled detection sandbox. This record exists only to demonstrate validation, normalization, retry, and fallback behavior.",
    publishedAt: new Date(Date.now() - index * 3600000).toISOString(),
    jobType: index % 3 === 0 ? "Full-time" : "Job",
  }));
}
